dist: trusty
sudo: false
language: cpp

compiler:
 - clang
 - gcc 

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-12.1
      env:
         - MATRIX_EVAL="CC=gcc-12.1 && CXX=g++-12.1"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-14.0
          packages:
            - clang++-14.0
      env:
         - MATRIX_EVAL="CC=clang++-14.0 && CXX=clang++-14.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cmake . 
  - cmake --build .