dist: trusty
root: false
language: cpp

compiler:
 - clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-14.0
          packages:
            - clang++-14.0
      env:
         - MATRIX_EVAL="CC=clang++-14.0 && CXX=clang++-14.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cmake . 
  - cmake --build .